services:
  lecture_chooser:
    image: lecture-chooser:latest
    container_name: lecture_chooser
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY:-please-change-me}
      # DATA_DIR: /app/app/data  # odkomentuj, jeśli pliki danych są w innym katalogu niż domyślny (app/data w WORKDIR /app)
    restart: unless-stopped
